FROM node:22.4-alpine AS build

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install --silent

COPY . .

RUN npm run build

FROM nginx
COPY --from=build /usr/src/app/build /usr/share/nginx/html