apiVersion: v1
kind: Service
metadata:
  name: blogapp-service
spec:
  selector:
    app: blogapp 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 7000
    targetPort: 7000
    nodePort: 31111